### ISSUE TITLE
AdvancedCalendarController.custom sets month incorrectly

### ISSUE THREAD

**Issue by qwixilver** [alex-melnyk/flutter_advanced_calendar#1]
Hello!

First I want to say that so far I _love_ the widget! It seems very well executed, and it's simple to integrate with existing forms due to being handled by a controller. However, when I try to set the controller to a custom date it would seem that it sets the month only to the current month. If I subsequently tap on a date in the calendar strip it will update the month correctly. 

Thanks for your help with this!

**Comment by alex-melnyk** [comment]
Thanks for reporting the issue was fixed on v0.0.4 keep me posted if not.
