### ISSUE TITLE
Animation performance is poor.

### ISSUE THREAD

**Issue by sleepinglion-dev** [alex-melnyk/flutter_advanced_calendar#23]
This project is great.

The animation of the transition from month mode to week mode is fantastic.

But the fps is very low.

Changing just one line of code will improve performance.

widget.dart file - 180 line

return SizedBox(

-> 

return AnimatedContainer(
      duration : _animationController.duration

But still not enough.

Any other ideas to improve performance?

**Comment by alex-melnyk** [comment]
No, if you have some ideas, please provide yours PR, than I can review it and publish to a new version.
