### ISSUE TITLE
Line Height options

### ISSUE THREAD

**Issue by qwixilver** [alex-melnyk/flutter_advanced_calendar#4]
I really wish I could give you a thumbs up twice on pub.dev this is such a great plugin! In almost every case it does things exactly the way I would do them if I had written it. Unfortunately I am seeing a bit of an issue at this point. When specifying the weekLineHeight if it is smaller than the default 32 the text will overflow. in addition to this if I specify a much larger size the widget scales, but the text does not. 

Also, as a side note - are there any plans to make the widget theme able beyond light/dark? If for example I wanted to plug in my own theme info to make it mesh with my app a bit better.

Thank you for your help!

**Comment by alex-melnyk** [comment]
Hey, thanks for your interest in this plugin. A new version published with version 1.0.0, check this out:
https://pub.dev/packages/flutter_advanced_calendar/versions/1.0.1

Also, check the README.md file to get information about customization.
